# Generated by Django 4.2.23 on 2026-03-08 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='消息ID')),
                ('title', models.CharField(default='小龙记账', max_length=100, verbose_name='发送者名称')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('link_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='链接文本')),
                ('link_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='跳转链接')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '系统消息',
                'verbose_name_plural': '系统消息',
                'db_table': 'system_message',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='MessageReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.systemmessage', verbose_name='消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '消息已读状态',
                'db_table': 'system_message_read',
                'unique_together': {('user', 'message')},
            },
        ),
    ]
