# Generated by Django 4.2.23 on 2026-02-27 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, verbose_name='分类ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('type', models.CharField(choices=[('expense', '支出'), ('income', '收入')], default='expense', max_length=10, verbose_name='账单类型')),
                ('sort', models.IntegerField(default=0, verbose_name='排序权重')),
            ],
            options={
                'verbose_name': '账单分类',
                'db_table': 'transaction_category',
            },
        ),
        migrations.CreateModel(
            name='TransactionIcon',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, verbose_name='图标ID')),
                ('name', models.CharField(max_length=50, verbose_name='图标名称')),
                ('group', models.CharField(max_length=20, verbose_name='图标分组')),
            ],
            options={
                'verbose_name': '图标库',
                'db_table': 'transaction_icon',
            },
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('type', models.CharField(choices=[('expense', '支出'), ('income', '收入')], default='expense', max_length=10, verbose_name='账单类型')),
                ('date', models.DateField(verbose_name='消费日期')),
                ('time', models.TimeField(verbose_name='消费时间')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='地点')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.transactioncategory', verbose_name='所属分类ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='所属用户ID')),
            ],
            options={
                'verbose_name': '账单记录',
                'db_table': 'transaction_record',
            },
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.transactionicon', verbose_name='关联图标ID'),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='所属用户ID'),
        ),
    ]
