# Generated by Django 4.2.23 on 2026-03-08 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetIcon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='图标ID')),
                ('name', models.CharField(max_length=20, verbose_name='图标名称')),
                ('icon', models.CharField(max_length=50, verbose_name='图标代码')),
                ('bg_class', models.CharField(max_length=50, verbose_name='背景类名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资产图标',
                'db_table': 'transaction_asset_icon',
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('type', models.CharField(choices=[('expense', '支出'), ('income', '收入')], default='expense', max_length=10, verbose_name='账单类型')),
                ('sort', models.IntegerField(default=0, verbose_name='排序权重')),
                ('count', models.IntegerField(default=0, verbose_name='账单数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '账单分类',
                'db_table': 'transaction_category',
            },
        ),
        migrations.CreateModel(
            name='TransactionIcon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='图标ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='图标名称')),
                ('icon', models.CharField(blank=True, max_length=50, unique=True, verbose_name='图标值')),
                ('group', models.CharField(default='normal', max_length=20, verbose_name='图标分组')),
                ('type', models.CharField(default='all', max_length=10, verbose_name='适用类型')),
            ],
            options={
                'verbose_name': '图标库',
                'db_table': 'transaction_icon',
            },
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('type', models.CharField(choices=[('expense', '支出'), ('income', '收入')], default='expense', max_length=10, verbose_name='账单类型')),
                ('date', models.DateField(verbose_name='消费日期')),
                ('time', models.TimeField(verbose_name='消费时间')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='地点')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.transactioncategory', verbose_name='所属分类ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='所属用户ID')),
            ],
            options={
                'verbose_name': '账单记录',
                'db_table': 'transaction_record',
            },
        ),
        migrations.CreateModel(
            name='TransactionInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='发票ID')),
                ('name', models.CharField(max_length=100, verbose_name='抬头名称')),
                ('tax_id', models.CharField(max_length=50, verbose_name='税号')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='单位地址')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话号码')),
                ('bank', models.CharField(blank=True, max_length=100, null=True, verbose_name='开户银行')),
                ('account', models.CharField(blank=True, max_length=50, null=True, verbose_name='银行账号')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='发票金额')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='所属用户ID')),
            ],
            options={
                'verbose_name': '发票助手',
                'db_table': 'transaction_invoice',
            },
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.transactionicon', verbose_name='关联图标ID'),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='所属用户ID'),
        ),
        migrations.CreateModel(
            name='AssetAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='账户ID')),
                ('name', models.CharField(max_length=50, verbose_name='账户名称')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='账户余额')),
                ('type', models.CharField(choices=[('asset', '资产'), ('debt', '负债')], default='asset', max_length=10, verbose_name='账户类型')),
                ('is_included_in_total', models.BooleanField(default=True, verbose_name='是否计入总资产')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.asseticon', verbose_name='资产类型图标')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='所属用户ID')),
            ],
            options={
                'verbose_name': '资产账户',
                'db_table': 'transaction_asset',
            },
        ),
        migrations.CreateModel(
            name='TransactionBudget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='预算ID')),
                ('is_total', models.BooleanField(default=False, verbose_name='是否为总预算')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预算金额')),
                ('budget_type', models.CharField(choices=[('month', '月预算'), ('year', '年预算')], default='month', max_length=10, verbose_name='预算类型')),
                ('period', models.CharField(max_length=20, verbose_name='预算周期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.transactioncategory', verbose_name='关联分类ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='所属用户ID')),
            ],
            options={
                'verbose_name': '预算管理',
                'db_table': 'transaction_budget',
                'unique_together': {('user', 'category', 'budget_type', 'period', 'is_total')},
            },
        ),
    ]
