# Generated by Django 4.2.23 on 2026-03-30 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_account_id_user_gender_user_nickname_and_more'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangchainChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='消息ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('ai', 'AI')], max_length=10, verbose_name='角色')),
                ('type', models.CharField(choices=[('text', '纯文本'), ('text_image', '图文'), ('transaction', '账单卡片')], default='text', max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文本内容')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片地址')),
                ('extra_data', models.TextField(blank=True, null=True, verbose_name='额外结构化数据(JSON)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.transactionrecord', verbose_name='关联账单记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='所属用户ID')),
            ],
            options={
                'verbose_name': 'AI 对话记录',
                'db_table': 'transaction_langchain_chat',
                'ordering': ['create_time'],
            },
        ),
    ]
