# Generated by Django 4.2.23 on 2026-08-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_langchainchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langchainchatmessage',
            name='type',
            field=models.CharField(
                choices=[
                    ('text', '纯文本'),
                    ('text_image', '图文'),
                    ('transaction', '账单卡片'),
                    ('confirm', '确认卡片'),
                ],
                default='text',
                max_length=20,
                verbose_name='消息类型',
            ),
        ),
    ]
