# Generated by Django 4.2.23 on 2026-08-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_langchainchatmessage_type_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTraceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('plan_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('agent', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_trace_event',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
