# Generated by Django 4.2.23 on 2026-09-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_agenttraceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('plan_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('running', '运行中'), ('waiting_confirmation', '等待确认'), ('completed', '已完成'), ('failed', '失败'), ('partial', '部分完成')], default='running', max_length=32)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_trace',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
