# -*- coding: utf-8 -*-
from pathlib import Path

lines = []
a = lines.append

a('"""Fuwa Agent: LCEL pipeline + LangGraph create_react_agent."""')
a("")
a("from __future__ import annotations")
a("")
a("import asyncio")
a("from collections.abc import AsyncIterator")
a("")
a("from langchain_core.messages import AIMessage, HumanMessage, ToolMessage")
a("from langchain_core.runnables import RunnableBranch, RunnableLambda")
a("from langgraph.prebuilt import create_react_agent")
a("")
a("from account.ai.knowledge import kb")
a("from account.ai.llm import prompt")
a("from account.ai.llm.llm import AGENT_MAX_ITERATIONS, llm")
a("from account.ai.llm.llm_utils import extract_content, log_agent_exc")
a("from account.ai.llm.response import chat, to_api_dict")
a("from account.ai.llm.schemas import AGENT_ERROR_REPLY, DEFAULT_CHAT_REPLY, TextReply")
a("from account.ai.tools.finance_tools import build_finance_tools")
a("")
a("from .func import quick_agent_greeting_prompt")
a("")
a("# =============================================================================")
a("# 1. Constants / config")
a("# =============================================================================")
a("")
a("_STATUS = {")
a('    "create_bill": "\u9e2d\u9e2d\u6b63\u5728\u8bb0\u8d26...",')
a('    "update_bill": "\u9e2d\u9e2d\u6b63\u5728\u6539\u8d26\u5355...",')
a('    "query_bills": "\u9e2d\u9e2d\u6b63\u5728\u67e5\u8d26\u5355...",')
a('    "analyze_expense": "\u9e2d\u9e2d\u6b63\u5728\u7b97\u8d26...",')
a('    "create_budget": "\u9e2d\u9e2d\u6b63\u5728\u8bbe\u9884\u7b97...",')
a('    "update_budget": "\u9e2d\u9e2d\u6b63\u5728\u6539\u9884\u7b97...",')
a('    "query_budget": "\u9e2d\u9e2d\u6b63\u5728\u67e5\u9884\u7b97...",')
a("}")
a("")
a("")
a("def _graph_config() -> dict:")
a('    return {"recursion_limit": max(AGENT_MAX_ITERATIONS * 2 + 2, 10)}')
a("")
a("")
a("# =============================================================================")
a("# 2. LangGraph result adapter (messages -> output / intermediate_steps)")
a("# =============================================================================")
a("")
a("def _tool_call_id(tc) -> str:")
a("    if isinstance(tc, dict):")
a('        return str(tc.get("id") or "")')
a('    return str(getattr(tc, "id", "") or "")')
a("")
a("")
a("def _tool_call_name(tc) -> str:")
a("    if isinstance(tc, dict):")
a('        return str(tc.get("name") or "")')
a('    return str(getattr(tc, "name", "") or "")')
a("")
a("")
a("def _agent_result_from_state(state: dict) -> dict:")
a('    """LangGraph messages -> {output, intermediate_steps} for to_api_dict."""')
a('    messages = state.get("messages") or []')
a("    pending = {}")
a("    steps = []")
a("    for msg in messages:")
a('        if isinstance(msg, AIMessage) and getattr(msg, "tool_calls", None):')
a("            for tc in msg.tool_calls:")
a("                pending[_tool_call_id(tc)] = tc")
a("        elif isinstance(msg, ToolMessage):")
a("            tc = pending.get(str(msg.tool_call_id))")
a("            if tc is not None:")
a("                content = msg.content if isinstance(msg.content, str) else str(msg.content)")
a("                steps.append((tc, content))")
a('    output = extract_content(messages[-1]).strip() if messages else ""')
a('    return {"output": output, "intermediate_steps": steps}')
a("")
a("")
a("# =============================================================================")
a("# 3. Greeting short-circuit")
a("# =============================================================================")
a("")
a("def _try_greeting(text: str) -> str | None:")
a("    g = quick_agent_greeting_prompt(text)")
a("    if not g.is_greeting:")
a("        return None")
a("    raw = extract_content(llm.invoke(prompt.build_greeting_prompt(text, g.prompt)))")
a("    return TextReply(reply=raw or DEFAULT_CHAT_REPLY).reply")
a("")
a("")
a("def _prepare(payload: dict) -> dict:")
a('    text = payload.get("text") or payload.get("input") or ""')
a("    return {")
a('        "input": text,')
a('        "greeting": _try_greeting(text),')
a('        "user": payload.get("user"),')
a("    }")
a("")
a("")
a("def _greeting_result(state: dict) -> dict:")
a('    return {"output": state["greeting"], "intermediate_steps": []}')
a("")
a("")
a("# =============================================================================")
a("# 4. Built-in ReAct (create_react_agent + finance_tools)")
a("# =============================================================================")
a("")
a("def _run_react_agent(state: dict) -> dict:")
a('    """LCEL node: build create_react_agent per user and run."""')
a("    agent = create_react_agent(")
a("        llm,")
a('        build_finance_tools(state.get("user")),')
a("        prompt=prompt.REACT_SYSTEM,")
a("    )")
a("    graph_state = agent.invoke(")
a('        {"messages": [HumanMessage(content=state.get("input") or "")]},')
a("        config=_graph_config(),")
a("    )")
a("    return _agent_result_from_state(graph_state)")
a("")
a("")
a("# =============================================================================")
a("# 5. LCEL main chain: prepare -> greeting / ReAct -> API dict")
a("# =============================================================================")
a("")
a("_agent_chain = (")
a("    RunnableLambda(_prepare)")
a("    | RunnableBranch(")
a("        (")
a("            lambda s: s.get(\"greeting\") is not None,")
a("            RunnableLambda(_greeting_result) | RunnableLambda(to_api_dict),")
a("        ),")
a("        RunnableLambda(_run_react_agent) | RunnableLambda(to_api_dict),")
a("    )")
a(")")
a("")
a("")
a("# =============================================================================")
a("# 6. SSE event packing (status / token / agent_result)")
a("# =============================================================================")
a("")
a("async def _yield_text_events(text: str, steps: list) -> AsyncIterator[dict]:")
a("    for tc, _ in steps:")
a('        yield {"type": "status", "text": _STATUS.get(_tool_call_name(tc), "\u9e2d\u9e2d\u6b63\u5728\u601d\u8003...")}')
a("    for i in range(0, len(text), 2):")
a("        part = text[i : i + 2]")
a("        if part:")
a('            yield {"type": "token", "text": part}')
a("            await asyncio.sleep(0.02)")
a('    yield {"type": "agent_result", "data": {"output": text, "intermediate_steps": steps}}')
a("")
a("")
a("# =============================================================================")
a("# 7. Public API (Views should only call these)")
a("# =============================================================================")
a("")
a("def extract_accounting_info(text, user=None):")
a('    """Sync path for mini-program fallback."""')
a("    try:")
a('        return _agent_chain.invoke({"text": text, "user": user})')
a("    except Exception as e:")
a('        log_agent_exc("AGENT", e, input=(text or "")[:60])')
a("        out = chat(AGENT_ERROR_REPLY)")
a('        out["remark"] = text')
a("        return out")
a("")
a("")
a("async def astream_accounting(text, user=None) -> AsyncIterator[dict]:")
a('    """SSE: status / token / agent_result / error (H5 main path)."""')
a("    try:")
a('        state = _prepare({"text": text, "user": user})')
a('        if state.get("greeting") is not None:')
a('            async for event in _yield_text_events(state["greeting"], []):')
a("                yield event")
a("            return")
a("")
a("        result = await asyncio.to_thread(_run_react_agent, state)")
a('        async for event in _yield_text_events(result["output"], result["intermediate_steps"]):')
a("            yield event")
a("    except Exception as e:")
a('        log_agent_exc("AGENT", e, input=(text or "")[:60])')
a('        yield {"type": "error", "message": AGENT_ERROR_REPLY, "remark": text}')
a("")
a("")
a("def prewarm_runtime():")
a('    """Warm up knowledge base on app start."""')
a("    kb.prewarm()")
a("")

text = "\n".join(lines)
# Decode unicode escapes in STATUS strings etc.
text = text.encode("utf-8").decode("unicode_escape").encode("latin1").decode("utf-8") if False else text
# lines already contain real \uXXXX as two-char backslash-u in source of THIS generator;
# when THIS file is executed, Python interprets \u in the string literals above.
Path("account/ai/gateway/agent.py").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
b = Path("account/ai/gateway/agent.py").read_bytes()
print("has_duck_utf8", b"\xe9\xb8\xad\xe9\xb8\xad" in b)
print("line150", Path("account/ai/gateway/agent.py").read_text(encoding="utf-8").splitlines()[149])
