services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: account
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && 
             python manage.py migrate && 
             uvicorn accountsystem.asgi:application --host 0.0.0.0 --port 8899"
    # command: daphne -b 0.0.0.0 -p 8899 accountsystem.asgi:application
    volumes:
      - .:/app
    ports:
      - "8010:8899"
    expose:
      - 8899
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=account
      - DB_USER=root
      - DB_PASSWORD=root

  celery:
    build: .
    command: celery -A accountsystem worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - db

  celery-beat:
    build: .
    command: celery -A accountsystem beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf/cert:/etc/nginx/certs
      - ./nginx/conf/wx-sercret:/etc/nginx/wx-sercret
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8011:80"
      - "443:443"
    depends_on:
      - web

volumes:
  mysql_data:
