version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password --authentication-policy=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: account
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /wwwroot/accounting/mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - shared_network

  redis:
    image: redis:7.0-alpine
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    networks:
      - shared_network

  mini_app:
    container_name: accounting
    build: .
    # 按照您的要求，移除了迁移命令，直接启动服务
    command: gunicorn accountsystem.asgi:application --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8899 --access-logfile - --log-level info
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-production}
    volumes:
      - .:/app
    ports:
      - "8010:8899"
    expose:
      - 8899
    restart: always
    networks:
      - shared_network
    depends_on:
      - db
      - redis

  celery:
    container_name: celery
    build: .
    command: celery -A accountsystem worker --pool=prefork --concurrency=8 --loglevel=info -Q default
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-production}
    volumes:
      - .:/app
    restart: always
    depends_on:
      - mini_app
    networks:
      - shared_network

  celery-compute:
    container_name: celery-compute
    build: .
    command: celery -A accountsystem worker --pool=prefork --concurrency=8 --loglevel=info -Q compute
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-production}
    volumes:
      - .:/app
    restart: always
    depends_on:
      - mini_app
    networks:
      - shared_network
  
  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A accountsystem beat --loglevel=info
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-production}
    volumes:
      - .:/app
    restart: always
    depends_on:
      - mini_app
    networks:
      - shared_network
  
  celery-flower:
    container_name: celery-flower
    build: .
    command: celery -A accountsystem flower --port=5050 --basic_auth=admin:password
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-production}
    volumes:
      - .:/app
    ports:
      - "5050:5050"
    restart: always
    depends_on:
      - mini_app
    networks:
      - shared_network
  
  nginx:
    container_name: account_nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf/wx-sercret:/etc/nginx/wx-sercret
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mini_app
    networks:
      - shared_network
  
# 网络配置
networks:
  shared_network:
    driver: bridge

# volumes:
#   mysql_data:
