database:
  engine: django.db.backends.mysql
  name: account
  user: root
  password: LuLongXiang200554
  host: mysql_db
  port: 3306
  'OPTIONS':
    'charset': 'utf8mb4'

redis:
  host: redis_db
  port: 6379
  db: 0
  password: null
