# Generated by Django 4.2.23 on 2026-02-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('login_type', models.SmallIntegerField(default=1, verbose_name='登录类型')),
                ('third_party_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='第三方唯一标识')),
                ('refer_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='推荐码')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否认证')),
                ('role_id', models.IntegerField(blank=True, null=True, verbose_name='VIP角色ID')),
                ('avatar_url', models.TextField(blank=True, null=True, verbose_name='用户头像地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user',
            },
        ),
    ]
