# Generated by Django 4.2.23 on 2026-03-08 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='勋章ID')),
                ('category', models.CharField(default='成就', max_length=50, verbose_name='分类名称')),
                ('name', models.CharField(max_length=50, verbose_name='勋章名称')),
                ('description', models.TextField(verbose_name='达成条件描述')),
                ('icon', models.CharField(default='medal-o', max_length=50, verbose_name='图标名称')),
                ('requirement_type', models.CharField(choices=[('checkin', '打卡天数'), ('bill', '记账笔数'), ('budget', '预算设置'), ('asset', '资产账户')], default='checkin', max_length=20, verbose_name='解锁条件类型')),
                ('requirement_value', models.IntegerField(default=1, verbose_name='解锁条件数值')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '勋章',
                'verbose_name_plural': '勋章',
                'db_table': 'transaction_medal',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('login_type', models.SmallIntegerField(default=1, verbose_name='登录类型')),
                ('third_party_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='第三方唯一标识')),
                ('refer_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='推荐码')),
                ('self_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='自身邀请码')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否认证')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('role_id', models.IntegerField(blank=True, null=True, verbose_name='VIP角色ID')),
                ('avatar_url', models.TextField(blank=True, null=True, verbose_name='用户头像地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserMedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_time', models.DateTimeField(auto_now_add=True, verbose_name='解锁时间')),
                ('medal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.medal', verbose_name='勋章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户已解锁勋章',
                'verbose_name_plural': '用户已解锁勋章',
                'db_table': 'user_medal',
                'unique_together': {('user', 'medal')},
            },
        ),
        migrations.CreateModel(
            name='UserCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='打卡日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户打卡',
                'db_table': 'user_check_in',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
