# Generated by Django 4.2.23 on 2026-03-09 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='账号ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('men', '男'), ('women', '女')], default='men', max_length=10, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='个性签名'),
        ),
        migrations.CreateModel(
            name='UserPointRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='变动积分值')),
                ('direction', models.CharField(choices=[('income', '收入'), ('expense', '支出')], default='income', max_length=10, verbose_name='变动方向')),
                ('type', models.CharField(choices=[('checkin', '每日签到'), ('task', '完成任务'), ('exchange', '积分兑换'), ('refund', '积分退还'), ('system', '系统赠送')], max_length=20, verbose_name='业务类型')),
                ('description', models.CharField(max_length=255, verbose_name='变动描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'db_table': 'user_point_record',
                'ordering': ['-create_time'],
            },
        ),
    ]
