# Generated by Django 4.2.23 on 2026-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='自身邀请码'),
        ),
    ]
