# Generated by Django 4.2.23 on 2026-06-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_account_id_user_gender_user_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布位置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user.user', verbose_name='发布者')),
            ],
            options={
                'verbose_name': '社区帖子',
                'verbose_name_plural': '社区帖子',
                'db_table': 'user_community_post',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(verbose_name='图片地址')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='comment.userpost', verbose_name='所属帖子')),
            ],
            options={
                'verbose_name': '帖子图片',
                'verbose_name_plural': '帖子图片',
                'db_table': 'user_community_image',
            },
        ),
        migrations.CreateModel(
            name='UserNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('follow', '关注'), ('like', '点赞'), ('comment', '评论')], max_length=10, verbose_name='通知类型')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='关联内容ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='通知内容摘要')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='通知时间')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='发起用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='user.user', verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '社交通知',
                'verbose_name_plural': '社交通知',
                'db_table': 'user_community_notice',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_replies', to='comment.usercomment', verbose_name='父评论ID')),
                ('comment_root', models.ForeignKey(blank=True, db_column='root_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_replies', to='comment.usercomment', verbose_name='根评论ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comment.userpost', verbose_name='所属帖子')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_replies', to='user.user', verbose_name='被回复者ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.user', verbose_name='评论者')),
            ],
            options={
                'verbose_name': '社区评论',
                'verbose_name_plural': '社区评论',
                'db_table': 'user_community_comment',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='comment.userpost', verbose_name='所属帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='user.user', verbose_name='点赞者')),
            ],
            options={
                'verbose_name': '帖子点赞',
                'verbose_name_plural': '帖子点赞',
                'db_table': 'user_community_post_like',
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mutual', models.BooleanField(default=False, verbose_name='是否互关')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to='user.user', verbose_name='被关注者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to='user.user', verbose_name='关注者')),
            ],
            options={
                'verbose_name': '用户关注',
                'verbose_name_plural': '用户关注',
                'db_table': 'user_community_follow',
                'unique_together': {('user', 'followed_user')},
            },
        ),
    ]
